"""add_jsonb_columns_to_agent_signals

Revision ID: 3dee0b24c9f5
Revises: 0001
Create Date: 2026-05-05 04:15:50.685537

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3dee0b24c9f5"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agent_signals",
        sa.Column(
            "tech_indicator_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "agent_signals",
        sa.Column("tech_timeframe_votes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "agent_signals",
        sa.Column("geo_top_events", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "agent_signals",
        sa.Column(
            "geo_base_zone_explanation", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "agent_signals",
        sa.Column(
            "geo_quote_zone_explanation", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "agent_signals",
        sa.Column("geo_graph", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "agent_signals",
        sa.Column(
            "macro_top_calendar_events", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "agent_signals",
        sa.Column(
            "sentiment_stress_sources", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "agent_signals",
        sa.Column(
            "sentiment_stocktwits_breakdown", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agent_signals", "sentiment_stocktwits_breakdown")
    op.drop_column("agent_signals", "sentiment_stress_sources")
    op.drop_column("agent_signals", "macro_top_calendar_events")
    op.drop_column("agent_signals", "geo_graph")
    op.drop_column("agent_signals", "geo_quote_zone_explanation")
    op.drop_column("agent_signals", "geo_base_zone_explanation")
    op.drop_column("agent_signals", "geo_top_events")
    op.drop_column("agent_signals", "tech_timeframe_votes")
    op.drop_column("agent_signals", "tech_indicator_snapshot")
    # ### end Alembic commands ###
